const PhotoUniverse = require('../models/PhotoUniverse');
const User = require('../models/User');
const { GoogleGenerativeAI } = require('@google/generative-ai');

// Initialize AI for prompt enhancement
const genAI = new GoogleGenerativeAI(process.env.GOOGLE_AI_API_KEY);

/**
 * 🌌 PHOTO UNIVERSE CONTROLLER
 * Manages the creation of multi-subject, hyper-realistic scenes.
 */

// 1. Create a New Universe (Scene Setup)
exports.createUniverse = async (req, res) => {
    try {
        const {
            universeName,
            mainPets,
            companionPets,
            humans,
            scenario,
            composition,
            style,
            settings
        } = req.body;

        // Validate required fields
        if (!mainPets || mainPets.length === 0) {
            return res.status(400).json({ success: false, error: 'At least one main pet is required.' });
        }

        // Create the Universe document
        const newUniverse = new PhotoUniverse({
            userId: req.user.id,
            universeName,
            mainPets,
            companionPets,
            humans,
            scenario,
            composition,
            style,
            settings
        });

        // 🧠 GENERATE 10000X MEGA PROMPT
        const MegaPromptSystem = require('../services/MegaPromptSystem');

        // Prepare input for Mega Prompt
        const subjects = [];
        if (mainPets) mainPets.forEach(p => subjects.push({ type: 'pet', description: `${p.size || 'medium'} ${p.breed} ${p.species}` }));
        if (companionPets) companionPets.forEach(p => subjects.push({ type: 'pet', description: `${p.breed} ${p.species}` }));
        if (humans) humans.forEach(h => subjects.push({ type: 'human', description: `${h.ageGroup} ${h.gender}` }));

        const megaPrompt = MegaPromptSystem.generate({
            subjects,
            scenario: scenario.type ? `${scenario.type} (${scenario.subType || ''})` : 'studio',
            timeOfDay: scenario.timeOfDay || 'dawn',
            vibe: style.artistic || 'photorealistic',
            groupDynamics: (humans && humans.length > 1) ? 'friends' : 'family'
        });

        // Save the Mega Prompt
        newUniverse.generatedPrompt = {
            hyperRealistic: megaPrompt,
            simplified: `A scene with ${subjects.length} subjects in ${scenario.type}`,
            technical: `Generated by MegaPromptSystem v1.0`,
            keywords: [scenario.type, style.artistic]
        };

        // Save to DB
        await newUniverse.save();

        res.status(201).json({
            success: true,
            message: 'Photo Universe created successfully',
            universeId: newUniverse._id,
            generatedPrompt: megaPrompt,
            universe: newUniverse
        });

    } catch (error) {
        console.error('❌ Error creating universe:', error);
        res.status(500).json({ success: false, error: error.message });
    }
};

// 2. Generate Images for the Universe
exports.generateUniverseImages = async (req, res) => {
    try {
        const { universeId } = req.params;
        const universe = await PhotoUniverse.findById(universeId);

        if (!universe) {
            return res.status(404).json({ success: false, error: 'Universe not found' });
        }

        if (universe.userId.toString() !== req.user.id && !req.user.isAdmin) {
            return res.status(403).json({ success: false, error: 'Not authorized' });
        }

        universe.status = 'generating';
        await universe.save();

        // 🚀 SIMULATION OF GENERATION (Replace with actual API call to Higgsfield/Stable Diffusion)
        // In a real 100x scenario, this would call the external API.
        // For now, we simulate the successful response structure.

        const mockGeneratedImages = [
            {
                imageUrl: 'https://petmatch.fun/assets/generated/universe_mock_1.jpg', // Placeholder
                engine: 'higgsfield',
                quality: '8K',
                hasWatermark: false
            },
            {
                imageUrl: 'https://petmatch.fun/assets/generated/universe_mock_2.jpg', // Placeholder
                engine: 'higgsfield',
                quality: '8K',
                hasWatermark: false
            }
        ];

        // Update Universe with results
        universe.generatedImages.push(...mockGeneratedImages);
        universe.status = 'completed';
        await universe.save();

        res.json({
            success: true,
            message: 'Images generated successfully',
            images: mockGeneratedImages
        });

    } catch (error) {
        console.error('❌ Error generating universe images:', error);
        // Update status to failed if possible
        await PhotoUniverse.findByIdAndUpdate(req.params.universeId, { status: 'failed' });
        res.status(500).json({ success: false, error: error.message });
    }
};

// 3. Get User's Universes
exports.getMyUniverses = async (req, res) => {
    try {
        const universes = await PhotoUniverse.find({ userId: req.user.id })
            .sort({ createdAt: -1 });
        res.json({ success: true, universes });
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
};

// 4. Get Single Universe Detail
exports.getUniverseById = async (req, res) => {
    try {
        const universe = await PhotoUniverse.findById(req.params.id);
        if (!universe) return res.status(404).json({ success: false, error: 'Not found' });

        // Check privacy
        if (!universe.settings.isPublic && universe.userId.toString() !== req.user.id) {
            return res.status(403).json({ success: false, error: 'Private universe' });
        }

        res.json({ success: true, universe });
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
};
